twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - "@BaseAdmin/layouts/features/_bootstrap_5.html.twig"

when@test:
    twig:
        strict_variables: true