<?php

namespace App\Repository;

/**
 * ServiceEntityRepository
 *
 * @author Máximo Sojo <maxsojo13@gmail.com>
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class ServiceEntityRepository extends \Maximosojo\ToolsBundle\ORM\ServiceEntityRepository
{
    use EntityRepositoryTrait;
    
    public function getFormatPaginator()
    {
        return \Maximosojo\ToolsBundle\Model\Paginator\Paginator::FORMAT_ARRAY_STANDARD;
    }
}
