services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    # FOS
    FOS\UserBundle\Security\LoginManager:
        public: true
        arguments: ["@security.token_storage","@security.user_checker","@security.authentication.session_strategy","@request_stack"]

    Symfony\Component\HttpFoundation\Session\Session:
        public: true